# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: nivaldoandrade
# "service" is the name of this project. This will also be added to your AWS resource names.
service: api

provider:
  name: aws
  runtime: nodejs24.x
  memorySize: 128
  architecture: arm64
  region: sa-east-1
  environment:
    TABLE_NAME: !Ref ConnectionsTable
    URL_CONNECTIONS_WEBSOCKET_API: !Sub https://${WebsocketsApi}.execute-api.${self:provider.region}.amazonaws.com/${sls:stage}/
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:DeleteItem
            - dynamodb:Scan
          Resource: !GetAtt ConnectionsTable.Arn

package:
  individually: true


build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    exclude:
      - '@aws-sdk/*'
    external:
      - '@aws-sdk/*'


resources:
  Resources:
    ConnectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${sls:stage}-ConnectionsTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH



functions:
  connectionWS:
    handler: src/functions/connectionWS.handler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
  sendMessageWS:
    handler: src/functions/sendMessageWS.handler
    events:
      - websocket:
          route: sendMessage
      - websocket:
          route: connected
  gargabeColletionWS:
    handler: src/functions/gargabeColletionWS.handler
    events:
      - eventBridge:
          schedule: rate(10 minutes)


    # PODEMOS SETAR A ROUTE KEY DIRETAMENTE NA WEBSOCKET
    # events:
    #   - websocket: $connect
